### ISSUE TITLE
Where to add this to get it work?

### ISSUE THREAD

**Issue by JaroSound** [ESX-PUBLIC/ESX-Snippet#6]
Citizen.CreateThread(function()
    while true do
    Citizen.Wait(0)
        if IsPedInAnyPoliceVehicle(GetPlayerPed(PlayerId())) then
            local veh = GetVehiclePedIsUsing(GetPlayerPed(PlayerId()), false)
            if (GetPedInVehicleSeat(veh, -1) == GetPlayerPed(PlayerId())) then
                if PlayerData.job ~= nil and PlayerData.job.name ~= 'police' then
                  drawTxt("~r~It's against the rules for civilians to drive these vehicles!",0,1,0.5,0.8,0.6,255,255,255,255)
                  SetVehicleUndriveable(veh, true)
                end
            end
        end
    end
end)

Where can i add this part of code to get it work?

**Comment by TanguyOrtegat** [comment]
just in client side bottom of policejob

**Comment by JaroSound** [comment]
I did that but its not workin :(

**Comment by ElNelyo** [comment]
Fixed
